# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    valuesEntity:
        class: AppBundle\Entity\Values
    gridEntity:
        class: AppBundle\Entity\Grid
    tilesEntity:
        class: AppBundle\Entity\Tiles
        arguments: ['@tilesetEntity', '@tileEntity']

    eventTileLastPossibilityEntity:
        class: AppBundle\Entity\Event\TileLastPossibility
    eventTileSetEntity:
        class: AppBundle\Entity\Event\TileSet
    tileEntity:
        class: AppBundle\Entity\Tile
        arguments: ['@event_dispatcher', '@setTileEvent', '@deduceTileEvent']
    tilesetEntity:
        class: AppBundle\Entity\Tiles\Tileset

    deduceTileEvent:
        class: AppBundle\Event\DeduceTileEvent
        arguments: ['@eventTileLastPossibilityEntity']
    setTileEvent:
        class: AppBundle\Event\SetTileEvent
        arguments: ['@eventTileSetEntity']
#    sudokuSession:
#        class: Symfony\Component\HttpFoundation\Session\Session
#        factory: [AppBundle\Utils\SudokuSessionFactory, create]
#    sudokuSessionService:
#        class: AppBundle\Service\SudokuSessionService
#        factory: [AppBundle\Service\SudokuSessionServiceFactory, create]
#        arguments: ['@sudokuSession']

    sessionMarker:
        class: AppBundle\Utils\SessionMarker
        arguments: ['@session', '@logger']
    gridAggregate:
        class: AppBundle\Subscriber\GridAggregate
        arguments: ['@session']
        tags:
            - { name: kernel.event_subscriber } 
    valuesAggregate:
        class: AppBundle\Subscriber\ValuesAggregate
        arguments: ['@session']
        tags:
            - { name: kernel.event_subscriber } 
    tilesAggregate:
        class: AppBundle\Subscriber\TilesAggregate
        arguments: ['@session']
        tags: 
            - { name: kernel.event_subscriber }

    app.twig_extension:
        class: AppBundle\Utils\TwigExtension
        public: false
        tags:
            - { name: twig.extension }
