# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    valuesEntity:
        class: AppBundle\Entity\Values
    gridEntity:
        class: AppBundle\Entity\Grid
    tilesEntity:
        class: AppBundle\Entity\Tiles
        arguments: ['@tilesetEntity']
    groupsEntity:
        class: AppBundle\Entity\Groups
#        arguments: ['@groupEntity']

    tilesetEntity:
        class: AppBundle\Entity\Tiles\Tileset

    eventTileLastPossibilityEntity:
        class: AppBundle\Entity\Event\TileLastPossibility
    eventTileSetEntity:
        class: AppBundle\Entity\Event\TileSet

    deduceTileEvent:
        class: AppBundle\Event\DeduceTileEvent
        arguments: ['@eventTileLastPossibilityEntity']
    setTileEvent:
        class: AppBundle\Event\SetTileEvent
        arguments: ['@eventTileSetEntity']
    validateTileSetEvent:
        class: AppBundle\Event\ValidateTileSetEvent
        arguments: ['@eventTileSetEntity']

    sessionContent:
        class: AppBundle\Entity\Persistence\SessionContent
    gridSession:
        class: AppBundle\Persistence\GridSession
        arguments: ['@session']
        tags:
            -  { name: session.content }
    valuesSession:
        class: AppBundle\Persistence\ValuesSession
        arguments: ['@session']
        tags:
            -  { name: session.content }
    tilesSession:
        class: AppBundle\Persistence\TilesSession
        arguments: ['@session']
        tags:
            -  { name: session.content }

    sudokuSession:
        class: AppBundle\Persistence\SudokuSession
        arguments: ['@session', '@sessionContent']

    groupsService:
        class: AppBundle\Service\GroupsService
        arguments: ['@event_dispatcher', '@validateTileSetEvent', '@deduceTileEvent']
#        arguments: ['@event_dispatcher', '@setTileEvent', '@deduceTileEvent', '@valuesEntity']

#    tileService:
#        class: AppBundle\Service\TileService
#        arguments: ['@event_dispatcher', '@setTileEvent', '@deduceTileEvent', '@valuesEntity']
#    sudokuSessionService:
#        class: AppBundle\Service\SudokuSessionService
#        factory: [AppBundle\Service\SudokuSessionServiceFactory, create]
#        arguments: ['@sudokuSession']

    sessionMarker:
        class: AppBundle\Utils\SessionMarker
        arguments: ['@sudokuSession', '@logger']
    gridAggregate:
        class: AppBundle\Subscriber\GridAggregate
        arguments: ['@gridSession']
        tags:
            - { name: kernel.event_subscriber } 
    valuesAggregate:
        class: AppBundle\Subscriber\ValuesAggregate
        arguments: ['@valuesSession']
        tags:
            - { name: kernel.event_subscriber } 
    tilesAggregate:
        class: AppBundle\Subscriber\TilesAggregate
        arguments: ['@tilesSession']
        tags: 
            - { name: kernel.event_subscriber }

    app.twig_extension:
        class: AppBundle\Utils\TwigExtension
        public: false
        tags:
            - { name: twig.extension }
