# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    sudokuSession:
        class: Symfony\Component\HttpFoundation\Session\Session
        factory: [AppBundle\Utils\SudokuSessionFactory, create]
    sudokuSessionService:
        class: AppBundle\Service\SudokuSessionService
        arguments: ['@sudokuSession']

    gridAggregate:
        class: AppBundle\Subscriber\GridAggregate
        arguments: ['@sudokuSessionService']
        tags:
            - { name: kernel.event_subscriber } 
