# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    valuesEntity:
        class: AppBundle\Entity\Values
    gridEntity:
        class: AppBundle\Entity\Grid
        
#    sudokuSession:
#        class: Symfony\Component\HttpFoundation\Session\Session
#        factory: [AppBundle\Utils\SudokuSessionFactory, create]
#    sudokuSessionService:
#        class: AppBundle\Service\SudokuSessionService
#        factory: [AppBundle\Service\SudokuSessionServiceFactory, create]
#        arguments: ['@sudokuSession']

    gridAggregate:
        class: AppBundle\Subscriber\GridAggregate
#        arguments: ['@sudokuSessionService', '@gridEntity']
        arguments: ['@session']
#        calls:
#            - [setGrid, ['@gridEntity']]
        tags:
            - { name: kernel.event_subscriber } 
#    valuesAggregate:
#        class: AppBundle\Subscriber\ValuesAggregate
#        arguments: ['@sudokuSessionService', '@valuesEntity']
#        tags:
#            - { name: kernel.event_subscriber } 

    app.twig_extension:
        class: AppBundle\Utils\TwigExtension
        public: false
        tags:
            - { name: twig.extension }